### ISSUE TITLE
Shift key doesn't work?

### ISSUE THREAD

**Issue by hsauro** [adelhpour/NetworkEditorGUI#10]
If multiple nodes are placed on the screen, pressing the shift key should allow a user to select multiple objects at once. But this doesn't work in version 0.1.1.

The only way to select multiple objects is to use the mouse but this isn't sufficient in all cases. For example, selecting a group of nodes and unselecting one node is not possible.

**Comment by adelhpour** [comment]
The feature was present, but it was overshadowed by a bug. It's now fixed.
