### ISSUE TITLE
Can't move the reaction centroid

### ISSUE THREAD

**Issue by hsauro** [adelhpour/NetworkEditorGUI#101]
It is not possible to move the reaction centroid. Users should be able to move the centroid.

**Comment by adelhpour** [comment]
To become able to move a reaction (centroid) node, the user can right-click on that node and enable 'Independent Position' option. There was a bug with displaying the the right-click menu in this situation which is now fixed by PR #110

**Comment by adelhpour** [comment]
To become able to move a reaction (centroid) node, the user can right-click on that node and enable 'Independent Position' option. There was a bug with displaying the the right-click menu in this situation which is now fixed by PR #110
