### ISSUE TITLE
Wrong extension when save as

### ISSUE THREAD

**Issue by hsauro** [adelhpour/NetworkEditorGUI#2]
Do the following:

1. Start editor
2. Add nodes
3. Save (eg to network1.json)
4. Save As -> SBML
5. Save dialog comes up but insert network1.json in to the file name box
6. It should insert network1.xml into the file name box

**Comment by adelhpour** [comment]
The issue is fixed by [2722c89](https://github.com/adelhpour/NetworkEditorGUI/commit/2722c89e187bf5428a20134d7e7e65c2a65b429a).
